version: "3.7"

services:
  web:
    container_name: web_dev
    restart: unless-stopped
    env_file: .env
    image: nginx:1.14.2
    build:
      context: ./nginx
    depends_on:
      - php-fpm
    links:
      - php-fpm
    environment:
      - TIME_ZONE=Europe\Berlin
      - TIME_ZONE_PATH=Europe/Berlin
      - SERVER_NAME=localhost
      - NGINX_PORT=80
      - FASTCGI_HOST=php-fpm
      - FASTCGI_PORT=9000
      - DOCUMENT_ROOT=/var/www/public
    ports:
      - 80:80
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    command: /bin/bash -c "cd /root/setup/; /root/setup/start.sh"

  php-fpm:
    container_name: php-fpm
    restart: always
    env_file: .env
    image: php7.3-fpm:latest
    build:
      context: ./php-fpm
      args:
        - USER=${USER}
        - USER_GUID=${USER_GUID}
    environment:
      - USER=${USER}
      - USER_GUID=${USER_GUID}
      - TIME_ZONE=Europe\Berlin
      - TIME_ZONE_PATH=Europe/Berlin
    volumes:
      - ./:/var/www/
      # - ./php-fpm/timezone:/etc/timezone:ro
    command: /bin/bash -c "cd /root/setup/; /root/setup/start.sh"
    working_dir: /var/www/
