FROM debian:buster

LABEL maintainer="Sebastian Majchrzak <smajchrzak@msdat.de>"

RUN apt-get -qq update && \
    apt-get -yqq install \
    tzdata \
    nginx-extras 

#COPY timezone.sh /root/setup/start.sh
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.template /etc/nginx/conf.d/default.conf

RUN mkdir -p /root/setup
COPY start.sh /root/setup/start.sh
RUN chmod +x /root/setup/start.sh 

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80 443

STOPSIGNAL SIGTERM

#CMD ["nginx", "-g", "daemon off;"]